/**
 * Generates components/layout/logo-paths.ts from the official SES vector logo
 * (public/images/ses-logo-original.svg, served by the current saveenergysystems.com).
 * Paths 0–7 = the dashed arc, 8–14 = "SYSTEMS", 15–24 = "save energy".
 * Run: node scripts/build-logo.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";

const svg = readFileSync("public/images/ses-logo-original.svg", "utf8");
const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
if (paths.length !== 25) throw new Error(`Expected 25 paths, found ${paths.length}`);

const out = `// Generated by scripts/build-logo.mjs from public/images/ses-logo-original.svg. Do not edit by hand.
export const LOGO_VIEWBOX = "0 0 107 67";
/** Teal dashed arc (the "mark") */
export const arc = ${JSON.stringify(paths.slice(0, 8), null, 2)};
/** "SYSTEMS" (teal) */
export const systems = ${JSON.stringify(paths.slice(8, 15), null, 2)};
/** "save energy" (adapts to light/dark via currentColor) */
export const wordmark = ${JSON.stringify(paths.slice(15), null, 2)};
`;
writeFileSync("components/layout/logo-paths.ts", out);
console.log("logo-paths.ts written");
